name: python-ci
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6
            - name: set up python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'
            - name: show python version
              run: python --version
            - name: Run tests
              run: python -m unittest discover -s . -p '*_test.py' 